export const ASSETS_PATH = 'assets/';

export interface HeroDetails {
    name: string;
    path: string;
    details: string[];
    skipChance: number;
}

export enum HERO_DETAILS_TYPE {
    HERO_BODY = 'body',
    HERO_HAT = 'hat',
    HERO_EARRINGS = 'earrings',
    HERO_MOUTH = 'mouth',
    HERO_GLASSES = 'glasses',
}

export const HERO_BODY: HeroDetails = {
    name: HERO_DETAILS_TYPE.HERO_BODY,
    path: 'hero-avatar/body/',
    skipChance: 0,
    details: [
        'ape.svg',
        'hero.svg',
        'robot.svg',
        'shark.svg',
        'whale.svg',
        'zombie.svg',
    ],
}

export const HERO_HAT: HeroDetails = {
    name: HERO_DETAILS_TYPE.HERO_HAT,
    path: 'hero-avatar/hat/',
    skipChance: 60,
    details: [
        'Genius Scientist.svg',
        'alien.svg',
        'army helmet.svg',
        'bandage.svg',
        'bandana black.svg',
        'bandana blue.svg',
        'bandana brown.svg',
        'bandana green.svg',
        'bandana red.svg',
        'beret.svg',
        'big brain.svg',
        'bowler hat.svg',
        'canotier.svg',
        'captain.svg',
        'cat.svg',
        'cowboy hat brown.svg',
        'cowboy hat pink.svg',
        'crown.svg',
        'cylinder.svg',
        'devil.svg',
        'earflap.svg',
        'flowers.svg',
        'garisson cap.svg',
        'gladiator.svg',
        'halo.svg',
        'hat.svg',
        'headphones blue.svg',
        'headphones green.svg',
        'headphones grey.svg',
        'headphones pink.svg',
        'headphones red.svg',
        'headphones white.svg',
        'helmet black.svg',
        'helmet green.svg',
        'helmet grey.svg',
        'helmet red.svg',
        'helmet.svg',
        'hoodie cream.svg',
        'hoodie green.svg',
        'hoodie grey.svg',
        'hoodie white.svg',
        'idea.svg',
        'jocker.svg',
        'laurel wreath.svg',
        'leprechaun.svg',
        'nurse.svg',
        'panama black.svg',
        'panama blue.svg',
        'panama grey.svg',
        'panama pink.svg',
        'panama red.svg',
        'party hat dotes.svg',
        'party hat lines.svg',
        'pirate.svg',
        'propeller beanie.svg',
        'rasta.svg',
        'robin hood.svg',
        'sailor.svg',
        'santa.svg',
        'snapback black.svg',
        'snapback blue.svg',
        'snapback green.svg',
        'snapback red.svg',
        'student.svg',
        'tiara.svg',
        'viking.svg',
        'winter hat.svg',
        'witch hat.svg',
    ],
}

export const HERO_EARRINGS: HeroDetails = {
    name: HERO_DETAILS_TYPE.HERO_EARRINGS,
    path: 'hero-avatar/earrings/',
    skipChance: 90,
    details: [
        'anchor.svg',
        'cross.svg',
        'diamond.svg',
        'earrings.svg',
        'flash.svg',
        'gold ring.svg',
        'luck.svg',
        'plugs black.svg',
        'studs.svg',
    ],
}

export const HERO_MOUTH: HeroDetails = {
    name: HERO_DETAILS_TYPE.HERO_MOUTH,
    path: 'hero-avatar/mouth/',
    skipChance: 0,
    details: [
        'Dali.svg',
        'beard.svg',
        'bubble gum.svg',
        'cigar.svg',
        'medical mask black.svg',
        'medical mask blue.svg',
        'mouth angry.svg',
        'mouth classy.svg',
        'mouth clown.svg',
        'mouth confused.svg',
        'mouth cute.svg',
        'mouth disappointed.svg',
        'mouth disgruntled.svg',
        'mouth happy.svg',
        'mouth kiss.svg',
        'mouth lips.svg',
        'mouth poker face.svg',
        'mouth shark.svg',
        'mouth surprised.svg',
        'mouth tongue.svg',
        'mouth tooth.svg',
        'mouth vampire.svg',
        'mustache black.svg',
        'mustache brown.svg',
        'party horn.svg',
        'pipe.svg',
        'pizza.svg',
        'respirator.svg',
    ],
}

export const HERO_GLASSES: HeroDetails = {
    name: HERO_DETAILS_TYPE.HERO_GLASSES,
    path: 'hero-avatar/glasses/',
    skipChance: 0,
    details: [
        '3D.svg',
        'Wayfarer black.svg',
        'Wayfarer blue.svg',
        'Wayfarer brown.svg',
        'Wayfarer glass.svg',
        'Wayfarer green.svg',
        'Wayfarer red.svg',
        'Wayfarer sunny.svg',
        'aviator black.svg',
        'aviator blue.svg',
        'aviator brown.svg',
        'aviator glass.svg',
        'aviator green.svg',
        'aviator red.svg',
        'aviator sunny.svg',
        'cat eye black.svg',
        'cat eye blue.svg',
        'cat eye brown.svg',
        'cat eye glass.svg',
        'cat eye green.svg',
        'cat eye red.svg',
        'cat eye sunny.svg',
        'clubs.svg',
        'cyborg.svg',
        'deal with it.svg',
        'diamonds.svg',
        'fire.svg',
        'gamer.svg',
        'hearts.svg',
        'hypno.svg',
        'matrix.svg',
        'moneymaker.svg',
        'night visor.svg',
        'popstar.svg',
        'rave.svg',
        'retro party.svg',
        'shield.svg',
        'ski goggles.svg',
        'sleep mask.svg',
        'sniper.svg',
        'spades.svg',
        'sport.svg',
        'steampunk.svg',
        'swim mask.svg',
        'teashades black.svg',
        'teashades blue.svg',
        'teashades brown.svg',
        'teashades glass.svg',
        'teashades green.svg',
        'teashades red.svg',
        'teashades sunny.svg',
        'techno visor.svg',
    ],
}

export const HERO_DETAILS: HeroDetails[] = [
    HERO_BODY,
    HERO_HAT,
    HERO_MOUTH,
    HERO_EARRINGS,
    HERO_GLASSES,
];